### ISSUE TITLE
Can't interact with signs?!

### ISSUE THREAD

**Issue by paindrah** [APDevTeam/Movecraft#142]
Is anyone else experiencing this ?
Don't really know what's causing it (i am a noob).

Movecraft 6.0 works fine 

Could i get some help?

```[20:23:45 ERROR]: Could not pass event PlayerInteractEvent to Movecraft v7.0.0_Pre-Release-9
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:920) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(SourceFile:55) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(SourceFile:11) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at net.countercraft.movecraft.sign.CraftSign.onSignClick(CraftSign.java:62) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:128) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at net.countercraft.movecraft.sign.CraftSign.onSignClick(CraftSign.java:62) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
        ... 17 more```

**Comment by cccm5** [comment]
what server software are you running?

**Comment by paindrah** [comment]
> 
> 
> what server software are you running?

craftbukkit-1.12.2

**Comment by cccm5** [comment]
> >  what server software are you running?
>
> craftbukkit-1.12.2
If you can use bukkit, Spigot, or Paper. Craftbukkit lacks many important features, in this case the capacity to send action bar messages to players, which is causing the error you're seeing.

**Comment by paindrah** [comment]
> 
> 
> > > what server software are you running?
> > 
> > 
> > craftbukkit-1.12.2
> 
> If you can use bukkit, Spigot, or Paper. Craftbukkit lacks many important features, in this case the capacity to send action bar messages to players, which is causing the error you're seeing. I'll have to add something to prevent the plugin from loading on craftbukkit in the future.

wait but i am pretty sure i tried spigot and it didn't work maybe i just don t remember correctly

**Comment by cccm5** [comment]
The plugin should definitely work on Spigot (I've tried it). Try it and let me know if it does/doesn't break.

**Comment by paindrah** [comment]
> 
> 
> The plugin should definitely work on Spigot (I've tried it). Try it and let me know if anything changes.

ok

**Comment by paindrah** [comment]
> 
> 
> The plugin should definitely work on Spigot (I've tried it). Try it and let me know if anything changes.

oh wow yeah works fine hmm weird that movecraft 6.0 works on bukkit but ok

**Comment by cccm5** [comment]
The plugin was almost completely rewritten, and in that process made use of Bungee's chat API during the rewrite. Unfortunately this does not exist in CraftBukkit as it is designed to be a minimal implementation on top of vanilla.

**Comment by paindrah** [comment]
oh i see

**Comment by paindrah** [comment]
> 
> 
> The plugin was almost completely rewritten, and in that process made use of Bungee's chat API during the rewrite. Unfortunately this does not exist in CraftBukkit as it is designed to be a minimal implementation on top of vanilla.

also thank you very much
