### ISSUE TITLE
1.12.2 Startup Error and Disables itself.

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#16]
Using your "Movecraft-7 "
```
[12:58:05] [Server thread/INFO]: [Movecraft] Enabling Movecraft v6.0.0
[12:58:05] [Server thread/INFO]: [Movecraft] Recognized PilotTool setting of: 294
[12:58:05] [Server thread/INFO]: [Movecraft] Loading support for v1_12_R1
[12:58:05] [Server thread/ERROR]: Error occurred while enabling Movecraft v6.0.0 (Is it up to date?)
java.lang.NullPointerException: null
	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1209]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[12:58:05] [Server thread/INFO]: [Movecraft] Disabling Movecraft v6.0.0
```

**Comment by keough99** [comment]
Looks like a paper spigot issue if your using paper spigot

**Comment by cccm5** [comment]
Can I get a list of plugins and the name (and version) of your server software?

**Comment by FrozenBeard** [comment]
I am using Paper Spigot 1218 https://ci.destroystokyo.com/job/PaperSpigot/ 
I don't want to post a public list of my plugins but I can send them over discord.

**Comment by MrUniverseAP** [comment]
As @keough99  said it looks to be a paper spigot issue. Ill look but cc will probably figure it out first.

**Comment by FrozenBeard** [comment]
Wicked, was this able to be looked at?

**Comment by cccm5** [comment]
So I just tested it on 1.12 paper and it worked fine, are you sure your using my version?

**Comment by FrozenBeard** [comment]
I just re-downloaded it and put it on and it changed it to Movecraft v7.0.0, but it still fails to load. Did you change how the craft files are formatted? Ive still got all my old ones in here.
I do also have FAWE installed, if that may effect it https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/

Ill try disabling the folder and removing FAWE, this is the error again.
Im downloading from the "Releases" section on Github, is this the latest version? or is there a Jenkins somewhere?

```
[19:34:20] [Server thread/INFO]: [Movecraft] Enabling Movecraft v7.0.0
[19:34:20] [Server thread/INFO]: [Movecraft] Recognized PilotTool setting of: 294
[19:34:20] [Server thread/INFO]: [Movecraft] Loading support for v1_12_R1
[19:34:20] [Server thread/ERROR]: Error occurred while enabling Movecraft v7.0.0 (Is it up to date?)
java.lang.NullPointerException: null
	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[19:34:20] [Server thread/INFO]: [Movecraft] Disabling Movecraft v7.0.0
```

**Comment by cccm5** [comment]
I just updated that release this morning, so you're all up to date. Do you have siege enabled, and what version of worldguard do you have?

**Comment by FrozenBeard** [comment]
Good man, glad to see this project is going on! 
WorldGuard version 6.2.2-SNAPSHOT;1708-3a8e3e8
it may be 1 or 2 versions behind their latest dev.

As far as I know I have never enabled siege, it never seemed to work (Or no docs so I couldn't figure it out!) 
Config.yml, I didnt set half of these so they must have been populated (Good thing too, I hated that the configs were not auto populated with movecraft)

```
Locale: en
CompatibilityMode: true
SinkRateTicks: 20
SinkCheckTicks: 100
TracerRateTicks: 20
PilotTool: 294
WorldGuardBlockMoveOnBuildPerm: false
WorldGuardBlockSinkOnPVPPerm: false
ManOverBoardTimeout: 30
FireballLifespan: 6
FireballPenetration: false
DisableSpillProtection: false
RequireCreatePerm: true
TNTContactExplosives: false
DisableCrates: true
FadeWrecksAfter: 0
RepairTicksPerBlock: 10
RepairMoneyPerBlock: 10
BlockQueueChunkSize: 1000
AllowCrewSigns: true
SetHomeToCrewSign: false
WGCustomFlagsUsePilotFlag: false
WGCustomFlagsUseMoveFlag: false
WGCustomFlagsUseRotateFlag: false
WGCustomFlagsUseSinkFlag: false
TownyBlockMoveOnSwitchPerm: false
TownyBlockSinkOnNoPVP: false
TownyWorldHeightLimits:
  world:
    worldMin: -1
    worldMax: -1
    aboveTownSpawn: 96
    underTownSpawn: 255
```

**Comment by FrozenBeard** [comment]
Any luck?

**Comment by cccm5** [comment]
Could you check if this still happens on the latest release?

**Comment by keough99** [comment]
`21.01 07:58:56 [Server] INFO Enabling Movecraft v7.0.0_pre_release_2
21.01 07:58:56 [Server] INFO Recognized PilotTool setting of: 369
21.01 07:58:56 [Server] INFO Loading support for v1_12_R1
21.01 07:58:56 [Server] ERROR Error occurred while enabling Movecraft v7.0.0_pre_release_2 (Is it up to date?)
21.01 07:58:56 [Server] INFO java.lang.NullPointerException: null
21.01 07:58:56 [Server] INFO at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:231) ~[?:?]
21.01 07:58:56 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1310]
21.01 07:58:56 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
21.01 07:58:56 [Server] INFO Disabling Movecraft v7.0.0_pre_release_2`
when i tried installing paper on my server i got that

**Comment by FrozenBeard** [comment]
It seemed to boot! But I got in a ship and did /cruise south and it spammed the console to high hell, and it froze the player like it was teleporting them 1000 times a second, even if you /release you were stuck, and the console errors kept spamming, I had to relog to get out of being frozen/spam teleported.

An infinite amount of these errors when I tried to cruise.
```

[14:46:38] [Server thread/WARN]: [Movecraft] Task #1280 for Movecraft v7.0.0_pre_release_2 generated an exception
java.lang.NoSuchFieldError: tileEntityList
	at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.getTileEntity(IWorldHandler.java:347) ~[Movecraft.jar:?]
	at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.translateCraft(IWorldHandler.java:185) ~[Movecraft.jar:?]
	at net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:29) ~[Movecraft.jar:?]
	at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:61) ~[Movecraft.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by cccm5** [comment]
This *should* be fixed

**Comment by melvyn2** [comment]
I'm still getting this issue with the latest paper and latest release of movecraft.
