### ISSUE TITLE
Movecraft v7.0.0.1 : Class Exception ; Ship won't move after first movement.

### ISSUE THREAD

**Issue by Vic3x** [APDevTeam/Movecraft#389]
Hello guys,
I setupped a server with the eirik's fork of movecraft for minecraft 1.16.5.
The first time that I tried to move a ship everything was ok, the ship moved and the commands were also executed.
Then, I setupped more plugins for permissions, formatting etc. I tried to make a new ship, but after the first movement, this error was shown on the console.

> [23:45:12] [Server thread/WARN]: [Movecraft] Task #7412 for Movecraft v7.0.0.1_for_1.8.8-1.16.2 generated an exception
java.lang.ClassCastException: class java.lang.Byte cannot be cast to class org.bukkit.block.data.BlockData (java.lang.Byte is in module java.base of loader 'bootstrap'; org.bukkit.block.data.BlockData is in unnamed module of loader 'app')
at net.countercraft.movecraft.utils.WaterlogUtils.waterlogBlocksOnCraft(WaterlogUtils.java:27) ~[?:?]
at net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:268) ~[?:?]
at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:62) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:2991-Spigot-018b9a0-f3f3094]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:2991-Spigot-018b9a0-f3f3094]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[server.jar:2991-Spigot-018b9a0-f3f3094]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[server.jar:2991-Spigot-018b9a0-f3f3094]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[server.jar:2991-Spigot-018b9a0-f3f3094]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[server.jar:2991-Spigot-018b9a0-f3f3094]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:2991-Spigot-018b9a0-f3f3094]

It happens only with the ship in water.
I'm using Spigot 1.16.5.
Hope you can help me, thanks in advance :)

**Comment by cccm5** [comment]
Hi, you'll want to submit issues relating to a fork to that forks issue section.
