### ISSUE TITLE
Movecraft disabled during startup

### ISSUE THREAD

**Issue by ItsJuls** [APDevTeam/Movecraft#435]
downloaded movecraft for my server then it was disabled when i checked /plugins, i checked logs and saw this 
[06:59:32] [Server thread/INFO]: [Movecraft] Enabling Movecraft v7.0.0.2_for_1.8.8-1.17
[06:59:32] [Server thread/WARN]: [Movecraft] Could not save movecraftlang_en.properties to plugins/Movecraft/localisation/movecraftlang_en.properties because movecraftlang_en.properties already exists.
[06:59:32] [Server thread/WARN]: [Movecraft] Could not save movecraftlang_cz.properties to plugins/Movecraft/localisation/movecraftlang_cz.properties because movecraftlang_cz.properties already exists.
[06:59:32] [Server thread/WARN]: [Movecraft] Could not save movecraftlang_nl.properties to plugins/Movecraft/localisation/movecraftlang_nl.properties because movecraftlang_nl.properties already exists.
[06:59:32] [Server thread/ERROR]: Error occurred while enabling Movecraft v7.0.0.2_for_1.8.8-1.17 (Is it up to date?)
java.lang.IllegalArgumentException: Numerical block IDs are not supported by this version
	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:103) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1165]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1165]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1165]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1165]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1165]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1165]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1165]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1165]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1165]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[06:59:32] [Server thread/INFO]: [Movecraft] Disabling Movecraft v7.0.0.2_for_1.8.8-1.17

**Comment by cccm5** [comment]
You are not using a version from this repository
