### ISSUE TITLE
Plugin breaks down after a ship moves by 1 block

### ISSUE THREAD

**Issue by Matteeusch** [APDevTeam/Movecraft#442]
Hello, I've installed the 7.0.0.1 version of the plugin on my 1.16.5 server, everything seemed to work until I tried to move a ship, the console showed me this
[Movecraft] Task #10504 for Movecraft v7.0.0.1_for_1.8.8-1.16.2 generated an exception
java.lang.ClassCastException: class java.lang.Byte cannot be cast to class org.bukkit.block.data.BlockData (java.lang.Byte is in module java.base of loader 'bootstrap'; org.bukkit.block.data.BlockData is in unnamed module of loader 'app')
        at net.countercraft.movecraft.utils.WaterlogUtils.waterlogBlocksOnCraft(WaterlogUtils.java:27) ~[?:?]
        at net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:268) ~[?:?]
        at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-782]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Any idea on how to fix that or what might be the cause?

**Comment by cccm5** [comment]
This is not the correct repository for the version of the plugin you have installed.
