### ISSUE TITLE
Unable to Pilot; Lags upon attempt

### ISSUE THREAD

**Issue by ccorp2002** [APDevTeam/Movecraft#464]
**Describe the bug**
Inability to Pilot Movecraft vehicles on Latest paper,purpur,airplane 1.17.1. When attempting to Pilot a Craft, it slows the server to a crawl until Movecraft produces an error.

**To Reproduce**
1.Right click a craft-sign.
2. Wait a second or two. 
3. Check console

**Expected behavior**
Able to Pilot a Craft, with minimal lag while doing so.

**Logs**
[16:21:44 WARN]: [Movecraft] Task #481608 for Movecraft v8.0.0-a.4.2 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Runnable.run()" because "runnable" is null
        at net.countercraft.movecraft.processing.WorldManager.run(WorldManager.java:82) ~[Movecraft.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1426]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1426]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1589) ~[patched_1.17.1.jar:git-Purpur-1426]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1426]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1505) ~[patched_1.17.1.jar:git-Purpur-1426]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1298) ~[patched_1.17.1.jar:git-Purpur-1426]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1426]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Versions (please complete the following information):**
 - Movecraft: 8.0.0-a.4.2 by [cccm5, BaccaYarro, TylerS1066, eirik1996, drfiveminusmint, HumorousFool]
 - Java [AdoptOpenJDK 16.0.1]
 - Minecraft [1.17.1, git-Purpur-1426]

**Additional context**
It works perfectly fine on a testing-copy of the live server.

**Comment by TylerS1066** [comment]
Upon discussion with the reporter in discord, this appears to likely be an issue with their closed source addon and cannot be reproduced elsewhere.
