### ISSUE TITLE
Movecraft can't be enabled (1.18.2)

### ISSUE THREAD

**Issue by JXSnack** [APDevTeam/Movecraft#528]
**Describe the bug**
The plugin does not start.

**To Reproduce**
1. Start the server

**Expected behavior**
It works

**Versions (please complete the following information):**
 - Movecraft: 8.0.0 alpha 7
 - Addons: Movecraft-Cannons, Movecraft-Combat
 - Java 17
 - Minecraft 1.18.2

**Additional context**
Here's the error:
`Error occurred while enabling Movecraft v8.0.0-a.7 (Is it up to date?)
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
    at net.countercraft.movecraft.craft.type.TypeData.parseLimit(TypeData.java:461) ~[Movecraft-8.0.0-a.7.jar:?]
    at net.countercraft.movecraft.craft.type.TypeData.getRequiredBlockEntrySet(TypeData.java:515) ~[Movecraft-8.0.0-a.7.jar:?]
    at net.countercraft.movecraft.craft.type.property.RequiredBlockProperty.load(RequiredBlockProperty.java:55) ~[Movecraft-8.0.0-a.7.jar:?]
    at net.countercraft.movecraft.craft.type.CraftType.<init>(CraftType.java:814) ~[Movecraft-8.0.0-a.7.jar:?]
    at net.countercraft.movecraft.craft.CraftManager.loadCraftTypes(CraftManager.java:128) ~[Movecraft-8.0.0-a.7.jar:?]
    at net.countercraft.movecraft.craft.CraftManager.<init>(CraftManager.java:95) ~[Movecraft-8.0.0-a.7.jar:?]
    at net.countercraft.movecraft.craft.CraftManager.initialize(CraftManager.java:69) ~[Movecraft-8.0.0-a.7.jar:?]
    at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:213) ~[Movecraft-8.0.0-a.7.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-379]
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-379]
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:1016) ~[paper-1.18.2.jar:git-Paper-379]
    at org.bukkit.Bukkit.reload(Bukkit.java:909) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-379]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-379]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-379]
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-379]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-379]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-379]
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-379]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-379]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by JXSnack** [comment]
Found the issue.
I changed the minimum flyblock percent, but i set it to "3" instead of "3.0".

**Comment by TylerS1066** [comment]
The recent dev builds have a few more useful prints on craft type loading failures if you are having trouble hunting down an issue.
