### ISSUE TITLE
Ship wont cruise?

### ISSUE THREAD

**Issue by ThermoMagno** [APDevTeam/Movecraft#550]
I built a ship and it rotates all fine, but it wont cruise. This the error:

<html>
<body>

[13:16:08] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Movecraft v8.0.0-a.9
--
107 | java.util.IllegalFormatConversionException: d != java.lang.String
108 | at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4442) ~[?:?]
109 | at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2963) ~[?:?]
110 | at java.util.Formatter$FormatSpecifier.print(Formatter.java:2918) ~[?:?]
111 | at java.util.Formatter.format(Formatter.java:2689) ~[?:?]
112 | at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
113 | at java.lang.String.format(String.java:4143) ~[?:?]
114 | at net.countercraft.movecraft.craft.CraftManager.release(CraftManager.java:229) ~[Movecraft_8.0.0-a.8.jar:?]
115 | at net.countercraft.movecraft.listener.PlayerListener.onPlayerMove(PlayerListener.java:133) ~[Movecraft_8.0.0-a.8.jar:?]
116 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor13.execute(Unknown Source) ~[?:?]
117 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
118 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-171]
119 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
120 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
121 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1604) ~[?:?]
122 | at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
123 | at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
124 | at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
125 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-171]
126 | at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
127 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
128 | at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-171]
129 | at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-171]
130 | at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
131 | at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-171]
132 | at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-171]
133 | at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
134 | at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[paper-1.19.2.jar:git-Paper-171]
135 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[paper-1.19.2.jar:git-Paper-171]
136 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-171]
137 | at java.lang.Thread.run(Thread.java:833) ~[?:?]

</body>
</html>[13:16:08] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Movecraft v8.0.0-a.9
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4442) ~[?:?]
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2963) ~[?:?]
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2918) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2689) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
	at java.lang.String.format(String.java:4143) ~[?:?]
	at net.countercraft.movecraft.craft.CraftManager.release(CraftManager.java:229) ~[Movecraft_8.0.0-a.8.jar:?]
	at net.countercraft.movecraft.listener.PlayerListener.onPlayerMove(PlayerListener.java:133) ~[Movecraft_8.0.0-a.8.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor13.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-171]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1604) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:[119](https://exaroton.com/log/#L119)7) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-171]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TylerS1066** [comment]
Please re-submit this with the bug report template and fill out all information fields.
