### ISSUE TITLE
Can pilot craft just fine, but then try to move it, cruise or rotate it does this:

### ISSUE THREAD

**Issue by E1Brando** [APDevTeam/Movecraft#551]
Keep getting this error when I try to move or rotate crafts:

[22:35:35] [Server thread/WARN]: [Movecraft] Task #3 for Movecraft v7.0.0 generated an exception
java.lang.ClassCastException: java.util.TreeSet cannot be cast to org.bukkit.craftbukkit.v1_12_R1.util.HashTreeSet
        at net.countercraft.movecraft.compat.v1_12_R1.NextTickProvider.registerWorld(NextTickProvider.java:41) ~[?:?]
        at net.countercraft.movecraft.compat.v1_12_R1.NextTickProvider.getNextTick(NextTickProvider.java:52) ~[?:?]
        at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.removeTileEntity(IWorldHandler.java:278) ~[?:?]
        at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.getTiles(IWorldHandler.java:234) ~[?:?]
        at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.getTiles(IWorldHandler.java:225) ~[?:?]
        at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.translateCraft(IWorldHandler.java:176) ~[?:?]
        at net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:70) ~[?:?]
        at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-fa590fd]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [CraftScheduler.class:git-CatServer-1.12.2-fa590fd]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]

----------------------------------------------------------------------------------------------------------------------------------------------

I am using the following plugins:

Movecraft 7.0.0
Movecraft-Combat 1.5.4
Movecraft-Repair 0.3.0
Worldedit 6.1.10
Worldcraft-Warfare
Beaming 1.5.1
Movecraft-WorldGuard 0.2.2

**Comment by TylerS1066** [comment]
Please re-submit this with the bug report template and fill out all information fields.
