### ISSUE TITLE
Errors with moving and rotating crafts

### ISSUE THREAD

**Issue by E1Brando** [APDevTeam/Movecraft#552]
**Describe the bug**
I can pilot crafts perfectly fine, but gives me errors when I try to move (including cruising) or rotate the craft.

**To Reproduce**
1. Load up a spigot-forge server (both 1.12.2) I made my mine by following a youtube tutorial: [https://www.youtube.com/watch?v=0i4KaeOGHag&t=54s]
2. Add Movecraft v7.0.0 and all the corresponding addons and dependencies
3. Load up Minecraft 1.12.2 using the essential mod 
4. Construct a craft of any type
5. Pilot, then attempt to rotate (using helm or command)

**Expected behavior**
The server console will send the default affirmative message for successfully piloting a craft, however when an attempt to move or rotate the craft is made, the console will display a message saying Task [#3] has made an exception. Or something of that nature. The craft will not rotate, however the player will. When attempting to move I have found that it usually puts out the same error message, and the craft does not move (The same for cruising).
This is the error message:

[22:35:35] [Server thread/WARN]: [Movecraft] Task #3 for Movecraft v7.0.0 generated an exception
java.lang.ClassCastException: java.util.TreeSet cannot be cast to org.bukkit.craftbukkit.v1_12_R1.util.HashTreeSet
at net.countercraft.movecraft.compat.v1_12_R1.NextTickProvider.registerWorld(NextTickProvider.java:41) ~[?:?]
at net.countercraft.movecraft.compat.v1_12_R1.NextTickProvider.getNextTick(NextTickProvider.java:52) ~[?:?]
at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.removeTileEntity(IWorldHandler.java:278) ~[?:?]
at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.getTiles(IWorldHandler.java:234) ~[?:?]
at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.getTiles(IWorldHandler.java:225) ~[?:?]
at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.translateCraft(IWorldHandler.java:176) ~[?:?]
at net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:70) ~[?:?]
at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:62) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-fa590fd]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [CraftScheduler.class:git-CatServer-1.12.2-fa590fd]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]

**Screenshots**

![Screenshot 2022-09-28 164212](https://user-images.githubusercontent.com/114446108/192824333-ecdec60d-fea2-457d-9cbb-96c736db6ec4.png)

**Versions:**
 - Movecraft: [ 7.0.0]
 - Addons: [Movecraft-Combat v1.5.4, Movecraft-Repair v0.3.0, Movecraft-WorldGuard v0.2.2, Movecraft-Warfare v0.5.4, Beaming v1.5.1, worldedit-bukkit v6.1.9, worldguard-bukkit v6.2.2]
 - Java [jre-8u341-windows x64]
 - Minecraft [1.12.2]

**Additional context**
I've been trying to make a server that combines the awesome feature of Movecraft with mods and play them with friends, therefore I have had to use the mod: essential 1.12.2 in order to play the server without port forwarding or paying. This may be the reason for the errror, but I can't be certain. My experience with tech is very limited :1.
ith mods and play them with friends, therefore I have had to use the mod: essential 1.12.2 in order to play the server without port forwarding or paying. This may be the reason for the errror, but I can't be certain. My experience with tech is very limited :1.

**Comment by TylerS1066** [comment]
We do not support modded platforms, only spigot and it's derivatives (we highly recommend Paper for it's increased Movecraft performance).

You'll have to contact the developers of the hybrid platform (CatServer it seems to be in this instance) and ask them about their support of Spigot plugins and any incompatibilities that arise.
