### ISSUE TITLE
1.19.4 - WorldManager runnable is null

### ISSUE THREAD

**Issue by Fyrinlight** [APDevTeam/Movecraft#576]
**Describe the bug**
Upon attempting to pilot a craft, the server will freeze for upwards of 5 seconds, then nothing occurs and it puts out the following error in console.
```
[17:08:40 WARN]: [Movecraft] Task #20 for Movecraft v8.0.0_beta-1 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Runnable.run()" because "runnable" is null
        at net.countercraft.movecraft.processing.WorldManager.run(WorldManager.java:82) ~[Movecraft.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-509]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-509]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**To Reproduce**

1. Use any new Spigot or Paper build
2. Compile the 1.19.4 Movecraft
3. Run the server and attempt to pilot a craft

**Versions (please complete the following information):**
 - Movecraft: Movecraft v8.0.0_beta-1
 - Addons: Only Movecraft v8.0.0_beta-1
 - Java OpenJDK jdk-19.0.2
 - Minecraft: git-Paper-509 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: e338793)

**Additional context**
Issue also observed on CraftBukkit version 3728-Spigot-514cf03-15a3eac (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

**Comment by TylerS1066** [comment]
Please try the dev build here: https://github.com/APDevTeam/Movecraft/actions/runs/4647259392, I don't think that should happen...

**Comment by Fyrinlight** [comment]
I don't know if this is related, but leaving the server running eventually had a thread dump where movecraft opened 247 ForJoin threads waiting on IAsyncChunk.getState() future.

```
[21:00:33] [Paper Watchdog Thread/ERROR]: ------------------------------
[21:00:33] [Paper Watchdog Thread/ERROR]: Current Thread: ForkJoinPool.commonPool-worker-247
[21:00:33] [Paper Watchdog Thread/ERROR]: 	PID: 4979 | Suspended: false | Native: false | State: WAITING
[21:00:33] [Paper Watchdog Thread/ERROR]: 	Stack:
[21:00:33] [Paper Watchdog Thread/ERROR]: 		java.base@19.0.2/jdk.internal.misc.Unsafe.park(Native Method)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		java.base@19.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:557)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.cache.LocalCache$LoadingValueReference.waitForValue(LocalCache.java:3586)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.cache.LocalCache$Segment.waitForLoadingValue(LocalCache.java:2179)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2166)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.cache.LocalCache.get(LocalCache.java:3966)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4956)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.support.v1_19_R3.IAsyncChunk.getState(IAsyncChunk.java:42)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.CachedMovecraftWorld.getState(CachedMovecraftWorld.java:54)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.tasks.detection.validators.ForbiddenSignStringValidator.validate(ForbiddenSignStringValidator.java:26)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.tasks.detection.validators.ForbiddenSignStringValidator.validate(ForbiddenSignStringValidator.java:19)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.functions.DetectionPredicate.lambda$and$1(DetectionPredicate.java:38)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.functions.DetectionPredicate$$Lambda$12449/0x000000080337fa90.validate(Unknown Source)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.functions.DetectionPredicate.lambda$and$1(DetectionPredicate.java:34)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.functions.DetectionPredicate$$Lambda$12449/0x000000080337fa90.validate(Unknown Source)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.functions.DetectionPredicate.lambda$and$1(DetectionPredicate.java:34)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.functions.DetectionPredicate$$Lambda$12449/0x000000080337fa90.validate(Unknown Source)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		Movecraft.jar//net.countercraft.movecraft.processing.tasks.detection.DetectionTask$DetectAction.run(DetectionTask.java:351)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		java.base@19.0.2/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		java.base@19.0.2/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		java.base@19.0.2/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		java.base@19.0.2/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		java.base@19.0.2/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
[21:00:33] [Paper Watchdog Thread/ERROR]: 		java.base@19.0.2/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[21:00:33] [Paper Watchdog Thread/ERROR]: ------------------------------
```

**Comment by Fyrinlight** [comment]
The issue is due to currentTasks.pull timing out and returning null. The timeout on task query needs to check for null since a timeout will add a null entry. However, why currentTasks.pull is timing out is unknown.
