### ISSUE TITLE
java.lang.ClassNotFoundException: net.countercraft.movecraft.compat.v1_19_R3.IWorldHandler

### ISSUE THREAD

**Issue by SatireShadow** [APDevTeam/Movecraft#579]
**Describe the bug**
Plugin won't load on 1.19.4

**To Reproduce**
Trying to load the plugin.

**Expected behavior**
Plugin to run.
**Screenshots**
If applicable, add screenshots (or videos) to help explain your problem.

**Versions (please complete the following information):**
 - Movecraft: [e.g. 8.0.0 alpha 6]
 - Addons: NA
 - Java 19
 - Minecraft 1.19.4

**Additional context**
[08:23:12] [Server thread/INFO]: [Movecraft] Enabling Movecraft v8.0.0_beta-1
[08:23:12] [Server thread/INFO]: [Movecraft] [I] Recognized PilotTool setting of: COMPASS
[08:23:12] [Server thread/WARN]: java.lang.ClassNotFoundException: net.countercraft.movecraft.compat.v1_19_R3.IWorldHandler
[08:23:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185)
[08:23:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152)
[08:23:12] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[08:23:12] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:23:12] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:390)
[08:23:12] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:381)
[08:23:12] [Server thread/WARN]: 	at Movecraft_8.0.0_beta-1.jar//net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:144)
[08:23:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[08:23:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[08:23:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[08:23:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[08:23:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569)
[08:23:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480)
[08:23:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643)
[08:23:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442)
[08:23:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:344)
[08:23:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1120)
[08:23:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[08:23:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[08:23:12] [Server thread/ERROR]: [Movecraft] [I] Could not find support for this version.

**Comment by SatireShadow** [comment]
https://github.com/APDevTeam/Movecraft/actions/runs/4713680489 This devbuild works, for anyone with the same issue.
