### ISSUE TITLE
I'm not sure why, but it won't let me use movecraft

### ISSUE THREAD

**Issue by JakeyCmh** [APDevTeam/Movecraft#580]
To reproduce:
try using movecraft

expected behavior:
for it to work

Movecraft 8.0.0 beta-1
Movecraft Combat v1.0.0
Movecraft-space v1.7 (i think)
Minecraft 1.19.4
 Movecraft-CoreProtect
(i think that's it) 

I'm getting this error in console

[03:24:17 WARN]: java.lang.ClassNotFoundException: net.countercraft.movecraft.compat.v1_19_R3.IWorldHandler
[03:24:17 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[03:24:17 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[03:24:17 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[03:24:17 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[03:24:17 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[03:24:17 WARN]:        at Movecraft_8.0.0_beta-1.jar//net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:144)
[03:24:17 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[03:24:17 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[03:24:17 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[03:24:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[03:24:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[03:24:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[03:24:17 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[03:24:17 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[03:24:17 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[03:24:17 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[03:24:17 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[03:24:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[03:24:17 ERROR]: [Movecraft] Could not find support for this version.

**Comment by JakeyCmh** [comment]
AdvancedBan, AdvancedBanAutoBan, BanAnnouncer, Beaming, BungeeGuard, CMILib, CoreProtect, DiscordSRV, dynmap, Gringotts, Iris, Jobs, LuckPerms, Maintenance, Movecraft, Movecraft-CoreProtect, Movecraft-Space, My_Worlds, PlaceholderAPI, ProtocolLib, Retribution, SimplePortals, Spicord, Towny, UltimateAutoRestart, Vault, VentureChat, ViaBackwards, ViaVersion, VoidGen WorldEdit, WorldGuard, BKCommonlib

**Comment by TylerS1066** [comment]
> [Movecraft] Could not find support for this version.

Per the [release notes of 8.0.0 beta 1](https://github.com/APDevTeam/Movecraft/releases/tag/8.0.0_beta-1):
> This release supports the following Minecraft versions on all common Spigot forks (we recommend Paper for optimal Movecraft performance):
> - 1.19.3
> - 1.19.2
> - 1.18.2
> - 1.17.1
> - 1.16.5
> - 1.14.4

Per our [FAQ page](https://github.com/APDevTeam/Movecraft/wiki/Frequently-Asked-Questions), 1.19.4 is currently supported in the latest dev builds.  Please make sure you are running the latest version of your server software before using it (as Spigot made some breaking changes mid-1.19.4).
