### ISSUE TITLE
movecraft is not working

### ISSUE THREAD

**Issue by goriraaaa217** [APDevTeam/Movecraft#605]
movecraft is not working
when i use movecraft command or Sign its not work

error

[16:30:02 WARN]: [Movecraft] Task #41 for Movecraft v8.0.0_beta-2 generated an exception
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.countercraft.movecraft.support.AsyncChunk.of(AsyncChunk.java:40) ~[Movecraft_8.0.0-beta-2.jar:?]
        at net.countercraft.movecraft.processing.CachedMovecraftWorld.lambda$getChunk$1(CachedMovecraftWorld.java:108) ~[Movecraft_8.0.0-beta-2.jar:?]
        at net.countercraft.movecraft.util.CompletableFutureTask.run(CompletableFutureTask.java:16) ~[Movecraft_8.0.0-beta-2.jar:?]
        at net.countercraft.movecraft.processing.WorldManager.run(WorldManager.java:82) ~[Movecraft_8.0.0-beta-2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-466]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1482) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-466]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
        at net.countercraft.movecraft.support.AsyncChunk.of(AsyncChunk.java:38) ~[Movecraft_8.0.0-beta-2.jar:?]
        ... 11 more
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.IChunkAccess org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle(net.minecraft.world.level.chunk.ChunkStatus)'
        at net.countercraft.movecraft.support.v1_19_R3.IAsyncChunk.<init>(IAsyncChunk.java:35) ~[Movecraft_8.0.0-beta-2.jar:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
        at net.countercraft.movecraft.support.AsyncChunk.of(AsyncChunk.java:38) ~[Movecraft_8.0.0-beta-2.jar:?]
        ... 11 more

**Comment by TylerS1066** [comment]
Please reopen this issue and fully fill out the bug report template, including the server platform and build number.
