### ISSUE TITLE
Error in 8.0.0 beta 2

### ISSUE THREAD

**Issue by naviddehnavi** [APDevTeam/Movecraft#651]
**Describe the bug**
When i installed movecraft and all of its addons liset in spigot page, i saw an error when i was trying to run /movecraft cmd
and this is error in console:

```
[08:33:28] [Server thread/INFO]: Xnavid_dehnaviX issued server command: /movecraft
[08:33:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'movecraft' in plugin Movecraft v8.0.0_beta-3 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:877) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1924) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.bp(SourceFile:115) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1106) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

```
**To Reproduce**
/movecraft

**Expected behavior**
I want to run /movecraft without issue

**Screenshots**
![Annotation 2024-06-15 191913](https://github.com/APDevTeam/Movecraft/assets/165388077/d16e5a00-f604-4f48-9263-7035f7ce3bd6)

**Versions (please complete the following information):**
 - Movecraft: 8.0.0_beta-2
 - Addons: All addons writted in spigot page
 - Java JDK 21
 - Minecraft 1.20.1

**Additional context**
Nothing

**Comment by TylerS1066** [comment]
The error states that you are running Movecraft 8.0.0 beta 3, which [the release notes](https://github.com/APDevTeam/Movecraft/releases/tag/8.0.0_beta-3) clearly state is only compatible with 1.20.6, not 1.20.1.

**Comment by naviddehnavi** [comment]
> The error states that you are running Movecraft 8.0.0 beta 3, which [the release notes](https://github.com/APDevTeam/Movecraft/releases/tag/8.0.0_beta-3) clearly state is only compatible with 1.20.6, not 1.20.1.

If you use movecraft version 8.0.0 beta 2, will the problem be solved?

**Comment by TylerS1066** [comment]
> If you use movecraft version 8.0.0 beta 2, will the problem be solved?

As mentioned in [the release notes of 8.0.0 beta 2](https://github.com/APDevTeam/Movecraft/releases/tag/8.0.0_beta-2), it has been tested to work with 1.20.1.

**Comment by naviddehnavi** [comment]
I tested it, but it dosen't work. i tested it in another spigot 1.20.1 server with only movecraft, protocollib and worldedit plugin but still have an issue
