### ISSUE TITLE
Repar system is broken

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#69]
The repair system is broken. Instead if saving a repair state, this comes out in console:

[16:47:45 ERROR]: Could not pass event PlayerInteractEvent to Movecraft v7.0.0_pre_release_5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:879) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
        at com.sk89q.worldedit.CuboidClipboard.setBlock(CuboidClipboard.java:512) ~[?:?]
        at net.countercraft.movecraft.listener.WorldEditInteractListener.WEOnPlayerInteract(WorldEditInteractListener.java:249) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        ... 18 more

This also happens when I right left click the sign:

[16:51:01 ERROR]: Could not pass event PlayerInteractEvent to Movecraft v7.0.0_pre_release_5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:879) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
        at com.sk89q.worldedit.CuboidClipboard.setBlock(CuboidClipboard.java:512) ~[?:?]
        at net.countercraft.movecraft.listener.WorldEditInteractListener.WEOnPlayerInteract(WorldEditInteractListener.java:249) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        ... 18 more

**Comment by cccm5** [comment]
Is this with the latest release jar or a self built jar? As far as I know this is fixed upstream.

**Comment by eirikh1996** [comment]
It is with the latest release jar

**Comment by TylerS1066** [comment]
https://github.com/APDevTeam/Movecraft/issues/71 is newer, closing this so we only have one per core issue.
